spring:
  application:
    name: mobily-ecommerce

  datasource:
    url: jdbc:mysql://72.60.188.251:3306/ipv?useSSL=false&serverTimezone=UTC
    username: mohalhal
    password: "re9006#OP"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.example.mobilyecommerce: DEBUG
token:
  secret: FFEvJ($ePwE7ep6L6DRg(Du+U!@a7nh3FY*TTuf7tNIAzEvHjHn8cMD*uc+ENG3r
  access-time: 1d
  refresh-time: 10d

#spring:
#  application:
#    name: mobily-ecommerce
#
#  datasource:
#    url: ${DB_URL:jdbc:mysql://localhost:3306/mobily_ecommerce?useSSL=false&serverTimezone=UTC}
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:root}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.example.mobilyecommerce: DEBUG
#
#token:
#  secret: ${TOKEN_SECRET:default_secret_key}
#  access-time: ${ACCESS_TOKEN_TIME:5m}
#  refresh-time: ${REFRESH_TOKEN_TIME:10d}
#
#
#
##export DB_URL=jdbc:mysql://72.60.188.251:3306/ipv?useSSL=false&serverTimezone=UTC
##export DB_USERNAME=mohalhal
##export DB_PASSWORD='re9006#OP'
##
##export TOKEN_SECRET='FFEvJ($ePwE7ep6L6DRg(Du+U!@a7nh3FY*TTuf7tNIAzEvHjHn8cMD*uc+ENG3r'
##export ACCESS_TOKEN_TIME=5m
##export REFRESH_TOKEN_TIME=10d