spring:
  application:
    name: mobily-ecommerce

  datasource:
    url: ${BIGZERO_DB_URL}
    username: ${BIGZERO_DB_USER}
    password: ${BIGZERO_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.example.mobilyecommerce: DEBUG
server:
  port: ${SERVER_PORT}

token:
  secret: ${TOKEN_SECRET}
  access-time: ${TOKEN_ACCESS_TIME}
  refresh-time: ${TOKEN_REFRESH_TIME}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
